services:
  server:
    networks:
      - backend
    build:
      context: ./backend
    ports:
      - 9000:80
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: 'mysql:dbname=task;host=db'
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./backend/:/var/www/html/
  db:
    container_name: db  
    networks:
      - backend
    image: mariadb
    restart: always
    user: root
    volumes:
      - db-data:/var/lib/mysql
      - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - '3306:3306'
    healthcheck:
      test:  ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect",  "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db_secret:
    file: ./secrets/db.txt

volumes:
  db-data:

networks:
  backend: